tap "aquasecurity/trivy"
tap "bufbuild/buf"
tap "clojure/tools"
tap "git-chglog/git-chglog"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "sqldef/sqldef"
brew 'openssl'
brew 'mas'
brew "automake"
brew "python@3.11"
brew "awscli", link: false
brew "bazaar"
brew "glib"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "emacs"
brew "cask"
brew "python@3.12"
brew "direnv"
brew "docker"
brew "docker-compose", link: false
brew "fd"
brew "harfbuzz"
brew "libass"
brew "pango"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "gdk-pixbuf"
brew "ghq"
brew "git"
brew "git-secrets"
brew "go"
brew "gobject-introspection"
brew "gts"
brew "librsvg"
brew "graphviz"
brew "grep"
brew "guile"
brew "jq"
brew "k6"
brew "libfido2"
brew "libssh"
brew "maven"
brew "meilisearch"
brew "mkcert"
brew "mysql-client"
brew "mydumper"
brew "mysql@5.7"
brew "nghttp2"
brew "nvm"
brew "plantuml"
brew "redis"
brew "sqlc"
brew "tfenv"
brew "tmux"
brew "tree"
brew "wget"
brew "wireshark"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "aquasecurity/trivy/trivy"
brew "clojure/tools/clojure"
brew "git-chglog/git-chglog/git-chglog"
brew "leiningen"

cask "adoptopenjdk"
cask "google-chrome"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "ngrok"
cask "packetproxy"
cask "postman"
cask "skitch"
cask "slack"
cask 'zoom'
cask 'obsidian'
cask 'drawio'
cask 'visual-studio-code'
cask 'asana'
cask 'figma'
cask 'rectangle'
cask 'discord'
cask 'orbstack'
cask 'tomatobar'

mas 'Xcode', id: 497799835
mas 'Kindle', id: 302584613
mas 'Tailscale', id: 1475387142