#!/bin/sh

# secretlint check on staged files
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs secretlint --secretlintrc ~/.secretlintrc.json
